### ISSUE TITLE
If I use LcR2dbcRepository, I get the following error

### ISSUE THREAD

**Issue by wang-xiaowu** [lecousin/lc-spring-data-r2dbc#4]
> springboot: 2.5.6, lecousin-r2dbc: 0.4.0
```
Field lcClient in net.lecousin.reactive.data.relational.repository.LcR2dbcRepositoryFactoryBean required a bean of type 'net.lecousin.reactive.data.relational.LcReactiveDataRelationalClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'net.lecousin.reactive.data.relational.LcReactiveDataRelationalClient' in your configuration.
```
- repository
```
public interface TestEntityRepository extends LcR2dbcRepository<TestEntity, Long> {

    default Flux<TestEntity> findAllAndJoin(){
        return SelectQuery.from(TestEntity.class, "test1")
                .join("test2", "testId", "test2")
                .execute(getLcClient());
    }
}
```
- application.yml
```
spring:
  r2dbc:
    password: root
    username: root
    url: r2dbc:mysql://localhost:3306/bin-springreactive
```
- lc-reactive-data-relational.yaml
```
entities:
  - org.xiaowu.springdatar2dbc.entity:
      - onetomany:
          - TestEntity
      - manytoone:
          - TestEntity2
```
- Application
```
@EnableR2dbcRepositories(repositoryFactoryBeanClass = LcR2dbcRepositoryFactoryBean.class,
        basePackages = {"org.xiaowu.springdatar2dbc.mapper"})
public class SpringDataR2dbcApplication {

    public static void main(String[] args) {
        LcReactiveDataRelationalInitializer.init();
        SpringApplication.run(SpringDataR2dbcApplication.class, args);
    }
}
```
